# Generated by Neurodocker and Reproenv.

FROM ubuntu:22.04

# OCI metadata — GitHub Container Registry uses image.source to auto-link
# this package to the LASHiS GitHub repo (Code button on the package page,
# permissions inherited from the repo, package shown on repo sidebar).
LABEL org.opencontainers.image.source="https://github.com/thomshaw92/LASHiS" \
      org.opencontainers.image.description="LASHiS v2 — Longitudinal Automatic Segmentation of Hippocampal Subfields (Nipype workflow with ANTs + ASHS + FSL + UMC Utrecht 7T atlas bundled)" \
      org.opencontainers.image.licenses="GPL-3.0-or-later" \
      org.opencontainers.image.title="LASHiS" \
      org.opencontainers.image.version="2.0.0" \
      org.opencontainers.image.documentation="https://github.com/thomshaw92/LASHiS#readme" \
      org.opencontainers.image.authors="Thomas B Shaw <thomasbasilshaw@gmail.com>"

ENV LANG="en_US.UTF-8" \
    LC_ALL="en_US.UTF-8" \
    ND_ENTRYPOINT="/neurodocker/startup.sh"
RUN export ND_ENTRYPOINT="/neurodocker/startup.sh" \
    && apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           apt-utils \
           bzip2 \
           ca-certificates \
           curl \
           locales \
           unzip \
    && rm -rf /var/lib/apt/lists/* \
    && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG="en_US.UTF-8" \
    && chmod 777 /opt && chmod a+s /opt \
    && mkdir -p /neurodocker \
    && if [ ! -f "$ND_ENTRYPOINT" ]; then \
         echo '#!/usr/bin/env bash' >> "$ND_ENTRYPOINT" \
    &&   echo 'set -e' >> "$ND_ENTRYPOINT" \
    &&   echo 'export USER="${USER:=`whoami`}"' >> "$ND_ENTRYPOINT" \
    &&   echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi' >> "$ND_ENTRYPOINT"; \
    fi \
    && chmod -R 777 /neurodocker && chmod a+s /neurodocker
RUN apt-get update -qq \
           && apt-get install -y -q --no-install-recommends \
                  ca-certificates \
                  curl \
                  git \
                  python3 \
                  python3-pip \
                  unzip \
           && rm -rf /var/lib/apt/lists/*
ENV ANTSPATH="/opt/ants-2.6.2/" \
    PATH="/opt/ants-2.6.2:$PATH"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           ca-certificates \
           curl \
           unzip \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading ANTs ..." \
    && curl -fsSL -o ants.zip https://github.com/ANTsX/ANTs/releases/download/v2.6.2/ants-2.6.2-centos7-X64-gcc.zip \
    && unzip ants.zip -d /opt \
    && mv /opt/ants-2.6.2/bin/* /opt/ants-2.6.2 \
    && rm ants.zip
ENV FSLDIR="/opt/fsl-6.0.7.16" \
    PATH="/opt/fsl-6.0.7.16/bin:$PATH" \
    FSLOUTPUTTYPE="NIFTI_GZ" \
    FSLMULTIFILEQUIT="TRUE" \
    FSLTCLSH="/opt/fsl-6.0.7.16/bin/fsltclsh" \
    FSLWISH="/opt/fsl-6.0.7.16/bin/fslwish" \
    FSLLOCKDIR="" \
    FSLMACHINELIST="" \
    FSLREMOTECALL="" \
    FSLGECUDAQ="cuda.q"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           ca-certificates \
           curl \
           dc \
           file \
           libfontconfig1 \
           libfreetype6 \
           libgl1-mesa-dev \
           libgl1-mesa-dri \
           libglu1-mesa-dev \
           libgomp1 \
           libice6 \
           libopenblas0 \
           libxcursor1 \
           libxft2 \
           libxinerama1 \
           libxrandr2 \
           libxrender1 \
           libxt6 \
           nano \
           python3 \
           sudo \
           wget \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Installing FSL ..." \
    && curl -fsSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fslinstaller.py | python3 - -d /opt/fsl-6.0.7.16 -V 6.0.7.16
ENV C3DPATH="/opt/convert3d-1.0.0" \
    PATH="/opt/convert3d-1.0.0/bin:$PATH"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           ca-certificates \
           curl \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading Convert3D ..." \
    && mkdir -p /opt/convert3d-1.0.0 \
    && curl -fsSL https://sourceforge.net/projects/c3d/files/c3d/1.0.0/c3d-1.0.0-Linux-x86_64.tar.gz/download \
    | tar -xz -C /opt/convert3d-1.0.0 --strip-components 1
RUN git clone --depth 1 --branch v2.0.0 https://github.com/pyushkevich/ashs.git /opt/ashs
ENV ASHS_ROOT="/opt/ashs" \
    PATH="/opt/ashs/bin:$PATH"
COPY ["pyproject.toml", \
      "/opt/lashis/pyproject.toml"]
COPY ["README.md", \
      "/opt/lashis/README.md"]
COPY ["LICENSE", \
      "/opt/lashis/LICENSE"]
COPY ["lashis", \
      "/opt/lashis/lashis"]
RUN python3 -m pip install --break-system-packages /opt/lashis
RUN lashis --check-deps && lashis --help > /dev/null
WORKDIR /data
ENTRYPOINT ["/neurodocker/startup.sh"]

# Save specification to JSON.
RUN printf '{ \
  "pkg_manager": "apt", \
  "existing_users": [ \
    "root" \
  ], \
  "instructions": [ \
    { \
      "name": "from_", \
      "kwds": { \
        "base_image": "ubuntu:22.04" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "LANG": "en_US.UTF-8", \
        "LC_ALL": "en_US.UTF-8", \
        "ND_ENTRYPOINT": "/neurodocker/startup.sh" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "export ND_ENTRYPOINT=\\"/neurodocker/startup.sh\\"\\napt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    apt-utils \\\\\\n    bzip2 \\\\\\n    ca-certificates \\\\\\n    curl \\\\\\n    locales \\\\\\n    unzip\\nrm -rf /var/lib/apt/lists/*\\nsed -i -e '"'"'s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/'"'"' /etc/locale.gen\\ndpkg-reconfigure --frontend=noninteractive locales\\nupdate-locale LANG=\\"en_US.UTF-8\\"\\nchmod 777 /opt && chmod a+s /opt\\nmkdir -p /neurodocker\\nif [ ! -f \\"$ND_ENTRYPOINT\\" ]; then\\n  echo '"'"'#!/usr/bin/env bash'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'set -e'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'export USER=\\"${USER:=`whoami`}\\"'"'"' >> \\"$ND_ENTRYPOINT\\"\\n  echo '"'"'if [ -n \\"$1\\" ]; then \\"$@\\"; else /usr/bin/env bash; fi'"'"' >> \\"$ND_ENTRYPOINT\\";\\nfi\\nchmod -R 777 /neurodocker && chmod a+s /neurodocker" \
      } \
    }, \
    { \
      "name": "install", \
      "kwds": { \
        "pkgs": [ \
          "ca-certificates", \
          "curl", \
          "git", \
          "unzip", \
          "python3", \
          "python3-pip" \
        ], \
        "opts": null \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq \\\\\\n    && apt-get install -y -q --no-install-recommends \\\\\\n           ca-certificates \\\\\\n           curl \\\\\\n           git \\\\\\n           python3 \\\\\\n           python3-pip \\\\\\n           unzip \\\\\\n    && rm -rf /var/lib/apt/lists/*" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "ANTSPATH": "/opt/ants-2.6.2/", \
        "PATH": "/opt/ants-2.6.2:$PATH" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    ca-certificates \\\\\\n    curl \\\\\\n    unzip\\nrm -rf /var/lib/apt/lists/*\\necho \\"Downloading ANTs ...\\"\\ncurl -fsSL -o ants.zip https://github.com/ANTsX/ANTs/releases/download/v2.6.2/ants-2.6.2-centos7-X64-gcc.zip\\nunzip ants.zip -d /opt\\nmv /opt/ants-2.6.2/bin/* /opt/ants-2.6.2\\nrm ants.zip" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "FSLDIR": "/opt/fsl-6.0.7.16", \
        "PATH": "/opt/fsl-6.0.7.16/bin:$PATH", \
        "FSLOUTPUTTYPE": "NIFTI_GZ", \
        "FSLMULTIFILEQUIT": "TRUE", \
        "FSLTCLSH": "/opt/fsl-6.0.7.16/bin/fsltclsh", \
        "FSLWISH": "/opt/fsl-6.0.7.16/bin/fslwish", \
        "FSLLOCKDIR": "", \
        "FSLMACHINELIST": "", \
        "FSLREMOTECALL": "", \
        "FSLGECUDAQ": "cuda.q" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    bc \\\\\\n    ca-certificates \\\\\\n    curl \\\\\\n    dc \\\\\\n    file \\\\\\n    libfontconfig1 \\\\\\n    libfreetype6 \\\\\\n    libgl1-mesa-dev \\\\\\n    libgl1-mesa-dri \\\\\\n    libglu1-mesa-dev \\\\\\n    libgomp1 \\\\\\n    libice6 \\\\\\n    libopenblas0 \\\\\\n    libxcursor1 \\\\\\n    libxft2 \\\\\\n    libxinerama1 \\\\\\n    libxrandr2 \\\\\\n    libxrender1 \\\\\\n    libxt6 \\\\\\n    nano \\\\\\n    python3 \\\\\\n    sudo \\\\\\n    wget\\nrm -rf /var/lib/apt/lists/*\\n\\necho \\"Installing FSL ...\\"\\ncurl -fsSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fslinstaller.py | python3 - -d /opt/fsl-6.0.7.16 -V 6.0.7.16" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "C3DPATH": "/opt/convert3d-1.0.0", \
        "PATH": "/opt/convert3d-1.0.0/bin:$PATH" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "apt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    ca-certificates \\\\\\n    curl\\nrm -rf /var/lib/apt/lists/*\\necho \\"Downloading Convert3D ...\\"\\nmkdir -p /opt/convert3d-1.0.0\\ncurl -fsSL https://sourceforge.net/projects/c3d/files/c3d/1.0.0/c3d-1.0.0-Linux-x86_64.tar.gz/download \\\\\\n| tar -xz -C /opt/convert3d-1.0.0 --strip-components 1" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "git clone --depth 1 --branch v2.0.0 https://github.com/pyushkevich/ashs.git /opt/ashs" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "ASHS_ROOT": "/opt/ashs", \
        "PATH": "/opt/ashs/bin:$PATH" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          "pyproject.toml", \
          "/opt/lashis/pyproject.toml" \
        ], \
        "destination": "/opt/lashis/pyproject.toml" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          "README.md", \
          "/opt/lashis/README.md" \
        ], \
        "destination": "/opt/lashis/README.md" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          "LICENSE", \
          "/opt/lashis/LICENSE" \
        ], \
        "destination": "/opt/lashis/LICENSE" \
      } \
    }, \
    { \
      "name": "copy", \
      "kwds": { \
        "source": [ \
          "lashis", \
          "/opt/lashis/lashis" \
        ], \
        "destination": "/opt/lashis/lashis" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "python3 -m pip install --break-system-packages /opt/lashis" \
      } \
    }, \
    { \
      "name": "run", \
      "kwds": { \
        "command": "lashis --check-deps && lashis --help > /dev/null" \
      } \
    }, \
    { \
      "name": "workdir", \
      "kwds": { \
        "path": "/data" \
      } \
    }, \
    { \
      "name": "entrypoint", \
      "kwds": { \
        "args": [ \
          "/neurodocker/startup.sh" \
        ] \
      } \
    } \
  ] \
}' > /.reproenv.json
# End saving to specification to JSON.
